geekshop_rodin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets'))
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import login, registration, logout, profile

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True)

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.core.validators import validate_email
from django import forms
from users.models import User
from .validators import validate_email


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form - control py - 4", "placeholder": "Введите имя пользователя"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form - control py - 4", "placeholder": "Введите пароль", "max_length": 200}))

    def clean(self):
        cleaned_data = super(UserLoginForm, self).clean()
        username_passed = cleaned_data.get("username")
        username_req = "ivan"
        if not (username_req in username_passed):
            raise forms.ValidationError("Not a valid username. Try one more time")
        return username_passed

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control py-4", "placeholder": "Введите имя пользователя"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        "class": "form-control py-4", "placeholder": "Введите адрес эл. почты"}),
        validators=[validate_email]
    )
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control py-4", "placeholder": "Введите имя"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control py-4", "placeholder": "Введите фамилию"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control py-4", "placeholder": "Введите пароль"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control py-4", "placeholder": "Подтвердите пароль"}))

    # def clean_email(self):
    #     email_passed = self.cleaned_data.get("email")
    #     email_req = "exampledomain.com"
    #     if not (email_req in email_passed):
    #         raise forms.ValidationError("Not a valid email. Try one more time")
    #     return email_passed

    # def clean(self):
    #     cleaned_data = super(UserRegistrationForm, self).clean()
    #     email_passed = cleaned_data.get("email")
    #     email_req = "exampledomain.com"
    #     if not (email_req in email_passed):
    #         raise forms.ValidationError("Not a valid email. Try one more time")
    #     return email_passed

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'image')

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth
from django.contrib import messages
from baskets.models import Basket
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from django.contrib.auth.decorators import login_required


def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()

    context = {
        "title": "GeekShop - Авторизация",
        "form": form
    }
    return render(request, 'users\\login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Вы успешно зарегистрировались!")
            return HttpResponseRedirect(reverse('users:login'))
        else:
            print(form.errors)
    else:
        form = UserRegistrationForm()
    context = {
        "title": "GeekShop - Регистрация",
        "form": form
    }
    return render(request, 'users\\register.html', context)


@login_required
def profile(request):
    if request.method == "POST":
        form = UserProfileForm(instance=request.user, files=request.FILES, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("users:profile"))
    else:
        form = UserProfileForm(instance=request.user)

    context = {"title": "Geekshop - Профиль",
               "form": form,
               "baskets": Basket.objects.filter(user=request.user)
               }
    return render(request, "users\\profile.html", context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>

<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content %}
        {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
</body>
</html>

users/templates/users/login.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="utf-8"/>-->
<!--    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>-->
<!--    <meta name="description" content=""/>-->
<!--    <meta name="author" content=""/>-->
<!--    <title>GeekShop - Авторизация</title>-->
<!--    <link href="../css/auth-admin.css" rel="stylesheet"/>-->
<!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"-->
<!--            crossorigin="anonymous"></script>-->
<!--</head>-->
<!--<body class="bg-primary">-->
<!--<div id="layoutAuthentication">-->
<!--    <div id="layoutAuthentication_content">-->
<!--        <main>-->
<!--            <div class="container">-->
<!--                <div class="row justify-content-center">-->
<!--                    <div class="col-lg-5">-->
<!--                        <div class="alert alert-warning alert-dismissible fade show" role="alert"-->
<!--                             style="margin-top: 50px;">-->
<!--                            <strong>Holy guacamole!</strong> You should check in on some of those fields below.-->
<!--                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">-->
<!--                                <span aria-hidden="true">&times;</span>-->
<!--                            </button>-->
<!--                        </div>-->
<!--                        <div class="card shadow-lg border-0 rounded-lg mt-5">-->
<!--                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>-->
<!--                            </div>-->
<!--                            <div class="card-body">-->
<!--                                <form>-->
<!--                                    <div class="form-group">-->
<!--                                        <label class="small mb-1" for="inputEmailAddress">Имя пользователя</label>-->
<!--                                        <input class="form-control py-4" id="inputEmailAddress" type="email"-->
<!--                                               placeholder="Введите имя пользователя"/>-->
<!--                                    </div>-->
<!--                                    <div class="form-group">-->
<!--                                        <label class="small mb-1" for="inputPassword">Пароль</label>-->
<!--                                        <input class="form-control py-4" id="inputPassword" type="password"-->
<!--                                               placeholder="Введите пароль"/>-->
<!--                                    </div>-->
<!--                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">-->
<!--                                        <a class="small" href="#">Забыли пароль?</a>-->
<!--                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">-->
<!--                                    </div>-->
<!--                                </form>-->
<!--                            </div>-->
<!--                            <div class="card-footer text-center">-->
<!--                                <div class="small"><a href="register.html">Нужен аккаунт? Зарегистрируйся!</a></div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </main>-->
<!--    </div>-->
<!--</div>-->
<!--<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"-->
<!--        crossorigin="anonymous"></script>-->
<!--<script src="../js/auth-admin.js"></script>-->
<!--</body>-->
<!--</html>-->


{% extends 'users\base.html' %}
{% load static %}

{% block content %}
    <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        {% if messages or form.errors %}
                            <div class="alert {% if messages %} alert-success {% else %} alert-warning {% endif %} alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                                {% if messages %}
                                    {% for message in messages %}
                                        {{ message }}
                                    {% endfor %}
                                {% else %}
                                    {% for error in form.non_field_errors %}
                                        {{ error }}
                                    {% endfor %}
                                {% endif %}
<!--                            <strong>Holy guacamole!</strong> You should check in on some of those fields below.-->
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
<!--                        <div class="alert alert-warning alert-dismissible fade show" role="alert"-->
<!--                             style="margin-top: 50px;">-->
<!--                            <strong>Holy guacamole!</strong> You should check in on some of those fields below.-->
<!--                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">-->
<!--                                <span aria-hidden="true">&times;</span>-->
<!--                            </button>-->
<!--                        </div>-->
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:login' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя
                                        пользователя</label>
                                </div>
                                    {{ form.username }}
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                </div>
                                    {{ form.password }}
                                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                    <a class="small" href="#">Забыли пароль?</a>
                                    <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                </div>
                            </form>
<!--                                <form action="{% url 'users:login' %}" method="post">-->
<!--                                    {% csrf_token %}-->
<!--                                    <div class="form-group">-->
<!--                                        <label class="small mb-1" for="inputEmailAddress">Имя пользователя</label>-->
<!--                                        <input class="form-control py-4" id="inputEmailAddress" type="email"-->
<!--                                               placeholder="Введите имя пользователя"/>-->
<!--                                    </div>-->
<!--                                    <div class="form-group">-->
<!--                                        <label class="small mb-1" for="inputPassword">Пароль</label>-->
<!--                                        <input class="form-control py-4" id="inputPassword" type="password"-->
<!--                                               placeholder="Введите пароль"/>-->
<!--                                    </div>-->
<!--                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">-->
<!--                                        <a class="small" href="#">Забыли пароль?</a>-->
<!--                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">-->
<!--                                    </div>-->

<!--                                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">-->
<!--                                        <a class="small" href="#">Забыли пароль?</a>-->
<!--                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">-->
<!--                                    </div>-->
<!--                                </form>-->
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:registration' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}

users/templates/users/register.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="utf-8"/>-->
<!--    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>-->
<!--    <meta name="description" content=""/>-->
<!--    <meta name="author" content=""/>-->
<!--    <title>GeekShop - Регистрация</title>-->
<!--    <link href="../css/auth-admin.css" rel="stylesheet"/>-->
<!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"-->
<!--            crossorigin="anonymous"></script>-->
<!--</head>-->
<!--<body class="bg-primary">-->
<!--<div id="layoutAuthentication">-->
<!--    <div id="layoutAuthentication_content">-->
<!--        <main>-->
<!--            <div class="container">-->
<!--                <div class="row justify-content-center">-->
<!--                    <div class="col-lg-7">-->
<!--                        <div class="alert alert-warning alert-dismissible fade show" role="alert"-->
<!--                             style="margin-top: 50px;">-->
<!--                            <strong>Holy guacamole!</strong> You should check in on some of those fields below.-->
<!--                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">-->
<!--                                <span aria-hidden="true">&times;</span>-->
<!--                            </button>-->
<!--                        </div>-->
<!--                        <div class="card shadow-lg border-0 rounded-lg mt-5">-->
<!--                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>-->
<!--                            </div>-->
<!--                            <div class="card-body">-->
<!--                                <form>-->
<!--                                    <div class="form-row">-->
<!--                                        <div class="col-md-6">-->
<!--                                            <div class="form-group">-->
<!--                                                <label class="small mb-1" for="inputFirstName">Имя</label>-->
<!--                                                <input class="form-control py-4" id="inputFirstName" type="text"-->
<!--                                                       placeholder="Введите имя"/>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                        <div class="col-md-6">-->
<!--                                            <div class="form-group">-->
<!--                                                <label class="small mb-1" for="inputLastName">Фамилия</label>-->
<!--                                                <input class="form-control py-4" id="inputLastName" type="text"-->
<!--                                                       placeholder="Введите фамилию"/>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                    <div class="form-row">-->
<!--                                        <div class="col-md-6">-->
<!--                                            <label class="small mb-1" for="inputUsername">Имя пользователя</label>-->
<!--                                            <input class="form-control py-4" id="inputUsername" type="text"-->
<!--                                                   aria-describedby="usernameHelp"-->
<!--                                                   placeholder="Введите имя пользователя"/>-->
<!--                                        </div>-->
<!--                                        <div class="col-md-6">-->
<!--                                            <label class="small mb-1" for="inputEmailAddress">Адрес электронной-->
<!--                                                почты</label>-->
<!--                                            <input class="form-control py-4" id="inputEmailAddress" type="email"-->
<!--                                                   aria-describedby="emailHelp"-->
<!--                                                   placeholder="Введите адрес эл. почты"/>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                    <div class="form-row">-->
<!--                                        <div class="col-md-6">-->
<!--                                            <div class="form-group">-->
<!--                                                <label class="small mb-1" for="inputPassword">Пароль</label>-->
<!--                                                <input class="form-control py-4" id="inputPassword" type="password"-->
<!--                                                       placeholder="Введите пароль"/>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                        <div class="col-md-6">-->
<!--                                            <div class="form-group">-->
<!--                                                <label class="small mb-1" for="inputConfirmPassword">Подтверждение-->
<!--                                                    пароля</label>-->
<!--                                                <input class="form-control py-4" id="inputConfirmPassword"-->
<!--                                                       type="password" placeholder="Подтвердите пароль"/>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                    <div class="form-group mt-4 mb-0">-->
<!--                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">-->
<!--                                    </div>-->
<!--                                </form>-->
<!--                            </div>-->
<!--                            <div class="card-footer text-center">-->
<!--                                <div class="small"><a href="login.html">Уже есть аккаунт? Авторизоваться</a></div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </main>-->
<!--    </div>-->
<!--</div>-->
<!--<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"-->
<!--        crossorigin="anonymous"></script>-->
<!--<script src="../js/auth-admin.js"></script>-->
<!--</body>-->
<!--</html>-->


{% extends 'users\base.html' %}
{% load static %}

{% block content %}
    <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        {% if form.errors %}
                            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                                 style="margin-top: 50px;">
                                    {{ form.errors }}
<!--                                <strong>Holy guacamole!</strong> You should check in on some of those fields below.-->
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
<!--                        <div class="alert alert-warning alert-dismissible fade show" role="alert"-->
<!--                             style="margin-top: 50px;">-->
<!--                            <strong>Holy guacamole!</strong> You should check in on some of those fields below.-->
<!--                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">-->
<!--                                <span aria-hidden="true">&times;</span>-->
<!--                            </button>-->
<!--                        </div>-->
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:registration' %}" method="post">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1"
                                                   for="{{ form.first_name.id_for_label }}">Имя</label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1"
                                                   for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="inputUsername">Имя пользователя</label>
                                        {{ form.username }}
                                    </div>
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                            почты</label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1"
                                                   for="{{ form.password1.id_for_label }}">Пароль</label>
                                            {{ form.password1 }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                                пароля</label>
                                            {{ form.password2 }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-4 mb-0">
                                    <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                </div>
                            </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}