baskets/urls.py
from django.urls import path
from baskets.views import basket_add, basket_remove, basket_edit

app_name = 'baskets'

urlpatterns = [
    path('add/<int:product_id>/', basket_add, name='basket_add'),
    path('remove/<int:id>/', basket_remove, name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop_rodin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets'))
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products.views import products

app_name = 'products'

urlpatterns = [
    path('', products, name='index')
]

users/urls.py
from django.urls import path
from users.views import login, registration, logout, profile

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
]

products/models.py
from django.db import models

# модели - это таблицы в БД


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products_images', blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} | {self.category.name}'

products/views.py
from django.shortcuts import render
from products.models import Product, ProductCategory
import json


# Create your views here.


def index(request):
    context = {"title": "GeekShop"}
    return render(request, 'products\\index.html', context)


def products(request):
    # to_JSON = {
    #   "products" :
    #           [
    #             {
    #               "name": "Худи черного цвета с монограммами adidas Originals",
    #               "price": "6 090,00 руб.",
    #               "description": "Мягкая ткань для свитшотов. Стиль и комфорт – это образ жизни.",
    #                 "img": "vendor/img/products/Adidas-hoodie.png",
    #                 "is_available": True
    #             },
    #
    #             {
    #               "name": "Синяя куртка The North Face",
    #               "price": "23 725,00 руб.",
    #               "description": "Гладкая ткань. Водонепроницаемое покрытие. Легкий и теплый пуховый наполнитель.",
    #                 "img": "vendor/img/products/Blue-jacket-The-North-Face.png",
    #                 "is_available": False
    #             },
    #
    #             {
    #               "name": "Коричневый спортивный oversized-топ ASOS DESIGN",
    #               "price": "3 390,00 руб.",
    #               "description": "Материал с плюшевой текстурой. Удобный и мягкий.",
    #                 "img": "vendor/img/products/Brown-sports-oversized-top-ASOS-DESIGN.png",
    #                 "is_available": True
    #             },
    #
    #             {
    #               "name": "Черный рюкзак Nike Heritage",
    #               "price": "2 340,00 руб.",
    #               "description": "Плотная ткань. Легкий материал.",
    #                 "img": "vendor/img/products/Black-Nike-Heritage-backpack.png",
    #                 "is_available": True
    #             },
    #
    #             {
    #               "name": "Черные туфли на платформе с 3 парами люверсов Dr Martens 1461 Bex",
    #               "price": "13 590,00 руб.",
    #               "description": "Гладкий кожаный верх. Натуральный материал.",
    #                 "img": "vendor/img/products/Black-Dr-Martens-shoes.png",
    #                 "is_available": True
    #             },
    #
    #             {
    #               "name": "Темно-синие широкие строгие брюки ASOS DESIGN",
    #               "price": "2 890,00 руб.",
    #               "description": "Легкая эластичная ткань сирсакер Фактурная ткань.",
    #                 "img": "vendor/img/products/Dark-blue-wide-leg-ASOs-DESIGN-trousers.png",
    #                 "is_available": True
    #             }
    #
    #           ]
    # }
    # end_file = open("products.json", 'w')
    # json.dump(to_JSON, end_file)
    # end_file.close()

    context = {
        "title": "GeekShop - Каталог",
        "product_category": ProductCategory.objects.all(),
        "products": Product.objects.all()
    }
    # with open('products\\fixtures\products.json') as file:
    #     for product in file:
    #         context.update(json.loads(product))
    print(context.items())

    return render(request, 'products\\products.html', context)

products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' %}">{{ user.username }}
                            <i class="fas fa-user-circle"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="admin/admin.html">
                            <i class="fas fa-users-cog"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link" >{% now "jS F Y" %}</p>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link" >{% now "jS F Y" %}</p>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %} {% endblock %}

<!-- Footer -->
{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'js/basket.js' %}"></script>

</body>

</html>

products/templates/products/index.html
{% extends 'products\base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">GeekShop Store</h1>
                <p>
                    Новые образы и лучшие бренды на GeekShop Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

products/templates/products/products.html
{% extends 'products\base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">GeekShop</h1>
            <div class="list-group">
                {% for category in product_category %}
                <a href="#" class="list-group-item">{{category.name}}</a>
                {% endfor %}
<!--                <a href="#" class="list-group-item">Одежда</a>-->
<!--                <a href="#" class="list-group-item">Обувь</a>-->
<!--                <a href="#" class="list-group-item">Аксессуары</a>-->
<!--                <a href="#" class="list-group-item">Подарки</a>-->
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">

                {% for product in products %}

                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="#">
                                <img class="card-img-top" src="{{product.image.url}}" alt="There must be image">
<!--                                     src="{% static  product.img  %}"-->
                            </a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="#"> {{ product.name }} </a>
                                </h4>
                                <h5>{{ product.price }}</h5>
                                <p class="card-text"> {{ product.description }}</p>
                            </div>
                            <div class="card-footer text-center">
                                {% if product.quantity %}
                                <a class="btn btn-outline-success" href="{% url 'baskets:basket_add' product.id %}">
                                    Отправить в корзину
                                </a>
<!--                                <button type="button" class="btn btn-outline-success">-->
<!--                                    Отправить в корзину-->
<!--                                </button>-->
                                {% else %}
                                <button type="button" class="btn btn-outline-danger">
                                    Товара нет в наличии
                                </button>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                {% endfor %}

<!--                <div class="col-lg-4 col-md-6 mb-4">-->
<!--                    <div class="card h-100">-->
<!--                        <a href="#">-->
<!--                            <img class="card-img-top"-->
<!--                                 src="{% static 'vendor/img/products/Blue-jacket-The-North-Face.png' %}" alt="">-->
<!--                        </a>-->
<!--                        <div class="card-body">-->
<!--                            <h4 class="card-title">-->
<!--                                <a href="#">Синяя куртка The North Face</a>-->
<!--                            </h4>-->
<!--                            <h5>23 725,00 руб.</h5>-->
<!--                            <p class="card-text">-->
<!--                                Гладкая ткань. Водонепроницаемое покрытие. Легкий и теплый пуховый наполнитель.-->
<!--                            </p>-->
<!--                        </div>-->
<!--                        <div class="card-footer text-center">-->
<!--                            <button type="button" class="btn btn-outline-danger">Удалить из корзины</button>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

<!--                <div class="col-lg-4 col-md-6 mb-4">-->
<!--                    <div class="card h-100">-->
<!--                        <a href="#">-->
<!--                            <img class="card-img-top"-->
<!--                                 src="{% static 'vendor/img/products/Brown-sports-oversized-top-ASOS-DESIGN.png' %}"-->
<!--                                 alt="">-->
<!--                        </a>-->
<!--                        <div class="card-body">-->
<!--                            <h4 class="card-title">-->
<!--                                <a href="#">Коричневый спортивный oversized-топ ASOS DESIGN</a>-->
<!--                            </h4>-->
<!--                            <h5>3 390,00 руб.</h5>-->
<!--                            <p class="card-text">Материал с плюшевой текстурой. Удобный и мягкий.</p>-->
<!--                        </div>-->
<!--                        <div class="card-footer text-center">-->
<!--                            <button type="button" class="btn btn-outline-success">Отправить в корзину</button>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

<!--                <div class="col-lg-4 col-md-6 mb-4">-->
<!--                    <div class="card h-100">-->
<!--                        <a href="#">-->
<!--                            <img class="card-img-top"-->
<!--                                 src="{% static 'vendor/img/products/Black-Nike-Heritage-backpack.png' %}"-->
<!--                                 alt="">-->
<!--                        </a>-->
<!--                        <div class="card-body">-->
<!--                            <h4 class="card-title">-->
<!--                                <a href="#">Черный рюкзак Nike Heritage</a>-->
<!--                            </h4>-->
<!--                            <h5>2 340,00 руб.</h5>-->
<!--                            <p class="card-text">Плотная ткань. Легкий материал.</p>-->
<!--                        </div>-->
<!--                        <div class="card-footer text-center">-->
<!--                            <button type="button" class="btn btn-outline-success">Отправить в корзину</button>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

<!--                <div class="col-lg-4 col-md-6 mb-4">-->
<!--                    <div class="card h-100">-->
<!--                        <a href="#">-->
<!--                            <img class="card-img-top"-->
<!--                                 src="{% static 'vendor/img/products/Black-Dr-Martens-shoes.png' %}"-->
<!--                                 alt="">-->
<!--                        </a>-->
<!--                        <div class="card-body">-->
<!--                            <h4 class="card-title">-->
<!--                                <a href="#">Черные туфли на платформе с 3 парами люверсов Dr Martens 1461 Bex</a>-->
<!--                            </h4>-->
<!--                            <h5>13 590,00 руб.</h5>-->
<!--                            <p class="card-text">Гладкий кожаный верх. Натуральный материал.</p>-->
<!--                        </div>-->
<!--                        <div class="card-footer text-center">-->
<!--                            <button type="button" class="btn btn-outline-success">Отправить в корзину</button>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

<!--                <div class="col-lg-4 col-md-6 mb-4">-->
<!--                    <div class="card h-100">-->
<!--                        <a href="#">-->
<!--                            <img class="card-img-top"-->
<!--                                 src="{% static 'vendor/img/products/Dark-blue-wide-leg-ASOs-DESIGN-trousers.png' %}"-->
<!--                                 alt="">-->
<!--                        </a>-->
<!--                        <div class="card-body">-->
<!--                            <h4 class="card-title">-->
<!--                                <a href="#">Темно-синие широкие строгие брюки ASOS DESIGN</a>-->
<!--                            </h4>-->
<!--                            <h5>2 890,00 руб.</h5>-->
<!--                            <p class="card-text">Легкая эластичная ткань сирсакер Фактурная ткань.</p>-->
<!--                        </div>-->
<!--                        <div class="card-footer text-center">-->
<!--                            <button type="button" class="btn btn-outline-success">Отправить в корзину</button>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->

            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>

        </div>

    </div>

</div>
<!-- /.container -->
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2021</p>
    </div>
    <!-- /.container -->
</footer>
{% endblock %}